myplants/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plants/', include('plants.urls')),
]

plants/urls.py
from django.urls import path
from plants import views

app_name = 'plants'

urlpatterns = [
    path('', views.all_plants, name='all_plants'),
    path('<int:pk>', views.plant_detail, name='plant_detail'),
]

plants/models.py
from django.db import models


# Create your models here.
class Plant(models.Model):
    title = models.CharField(max_length=100, null=True)
    botanical_name = models.CharField(max_length=100, null=True)
    plant_type = models.CharField(max_length=100, null=True)
    mature_size = models.CharField(max_length=100, null=True)
    sun_exposure = models.CharField(max_length=100, null=True)
    soil_type = models.CharField(max_length=100, null=True)
    hardiness_zones = models.CharField(max_length=100, null=True)
    native_area = models.CharField(max_length=100, null=True)
    toxicity = models.CharField(max_length=100, null=True)
    notes = models.TextField(null=True)
    image = models.CharField(max_length=100, null=True)

plants/views.py
from django.shortcuts import render
from plants.models import Plant


# Create your views here.
def all_plants(request):
    # query the db to return all plant objects
    plants = Plant.objects.all()
    return render(request, 'plants/all_plants.html', {'plants': plants})

def plant_detail(request, pk):
    plant = Plant.objects.get(pk=pk)
    return render(request, 'plants/detail.html', {'plant': plant})

plants/templates/plants/all_plants.html
{% extends 'plants/base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <h1>Plants</h1>
    <div class="row">
    {% for plant in plants %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static plant.image %}" alt="image of the plant">
                <div class="card-body">
                     <h5 class="card-title"> {{ plant.title }}</h5>
                     <a href="{% url 'plants:plant_detail' plant.pk %}"
                        class="btn btn-primary">
                            Read More
                     </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

plants/templates/plants/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Plants</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'plants:all_plants' %}">Plants</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'plants:all_plants' %}">Home</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
{% block content %}

{% endblock %}
</div>
</body>
</html>

plants/templates/plants/detail.html
{% extends 'plants/base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h1>{{plant.title}}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static plant.image %}" alt="{{ plant.title }}">
        </div>
        <div class="col-md-4">
            <p class="card-text"> {{ plant.botanical_name }}</p>
            <p class="card-text"> {{ plant.plant_type }}</p>
            <p class="card-text"> {{ plant.mature_size }}</p>
            <p class="card-text"> {{ plant.sun_exposure }}</p>
            <p class="card-text"> {{ plant.soil_type }} </p>
            <p class="card-text"> {{ plant.sun_exposure }} </p>
            <p class="card-text"> {{ plant.hardiness_zones }} </p>
            <p class="card-text"> {{ plant.native_area }} </p>
            <p class="card-text"> {{ plant.toxicity }} </p>
            <p class="card-text"> {{ plant.notes }} </p>
        </div>
    </div>
</div>

{% endblock %}